### ISSUE TITLE
A tiny issue

### ISSUE THREAD

**Issue by bzhkl** [abhishekkr/tutorials_as_code#1]
tutorials_as_code/talks-articles/haskell/PhilipWadler-UniversityOfEdinburgh-2011/lecture18.example04.hs

oneof gs = do { i <- choose (0, length gs - 1); gs !! 1 }
should 
oneof gs = do { i <- choose (0, length gs - 1); gs !! i }
？

**Comment by abhishekkr** [comment]
thanks @bzhkl 
I went away from Haskell for couple year and am returning back, thus wasn't able to check it in between.
